micronaut:
  server:
    port: 8082

datasources:
  default:
    url: jdbc:h2:mem:planets_db;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true

graphql:
  graphiql:
    enabled: true
  graphql-ws:
    enabled: true
